languageCode = "en-us"
languageName = "English"
weight = 1

title = "Congo Test"
copyright = "&copy; 2023 Congo Test"

[params]
  isoCode = "en-US"
  displayName = ":flag-us:"
  rtl = false

  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[author]
  name = "Congo Test"
  image = "img/author.jpg"
  headline = "Not your ordinary theme!"
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { twitter = "https://twitter.com/" },
    { facebook = "https://facebook.com/" },
    { linkedin = "https://linkedin.com/" },
    { youtube = "https://youtube.com/" },
  ]
