backend:
  name: github
  repo: jorap/jorap.com
  branch: master
  base_url: https://www.jorap.com
  auth_endpoint: /api/auth

media_folder: static/images
public_folder: /images

collections:
  - name: blog
    label: Blog Posts
    folder: content/english/blog
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown