backend:
  name: test-repo

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "test"
    label: "Test Collection"
    folder: "content/test"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}