backend:
  name: github
  repo: jorap/jorap.com
  branch: master
  base_url: https://jorap.com
  auth_endpoint: /api/auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/english/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Title", name: "meta_title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: ["Website", "Technology", "Blog", "Tutorial", "Review", "Personal"]}
      - {label: "Author", name: "author", widget: "string", default: "JoRap"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "authors"
    label: "Authors"
    folder: "content/english/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Avatar", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Social Links"
        name: "social"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Icon", name: "icon", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
      - {label: "Bio", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "content/english/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta Title", name: "meta_title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "about"
    label: "About Page"
    files:
      - file: "content/english/about/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Meta Title", name: "meta_title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Draft", name: "draft", widget: "boolean", default: false}
          - {label: "Body", name: "body", widget: "markdown"} 