#!/usr/bin/env python3
"""Append would-you-rather and table-topics collections to data/randomizer.yaml."""
from __future__ import annotations

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
YAML = ROOT / "data" / "randomizer.yaml"
TARGET = 300

# ponytail: one-shot deck builder; re-run after editing WYR_* / TOPIC_* lists

WYR_META = {
    "id": "would-you-rather",
    "title": "Either-or dilemmas",
    "mode": "ranked-prompts",
    "tagline": "Two options, one choice. Pick a side and say why.",
    "play_hint": (
        "Read both options aloud. Everyone picks one — no middle ground. "
        "Best argument wins."
    ),
}

TABLE_META = {
    "id": "table-topics",
    "title": "Conversation starters",
    "mode": "ranked-prompts",
    "tagline": "Open prompts — share a story, a memory, or a hot take. No scoring.",
    "play_hint": (
        "Take turns answering. There is no right answer — stories beat one-word replies."
    ),
}

WYR_ITEMS: list[str] = [
    "Always be ten minutes early, or always be ten minutes late?",
    "Always have perfect weather on vacation, or always get the best seat at home?",
    "Always know the plot of a movie before you watch it, or never know anything about it?",
    "Always laugh at your own jokes, or never laugh at your own jokes?",
    "Always remember names, or always remember faces?",
    "Always sleep eight hours but wake up groggy, or sleep six hours and wake up refreshed?",
    "Always speak your mind, or always think before you speak?",
    "Always win at board games, or always have the most fun losing?",
    "Be able to fly but only two feet off the ground, or be invisible but only when nobody is looking?",
    "Be famous for one amazing thing, or be unknown but great at many things?",
    "Be the funniest person in the room, or the kindest person in the room?",
    "Be the best player on a losing team, or the worst player on a winning team?",
    "Be the first to arrive at every party, or the last to leave every party?",
    "Be the person who plans every trip, or the person who happily follows along?",
    "Be able to talk to animals, or speak every human language fluently?",
    "Be able to pause time for one minute a day, or rewind one minute a day?",
    "Be stuck in summer forever, or stuck in winter forever?",
    "Eat only breakfast foods for a year, or eat only dinner foods for a year?",
    "Eat the same perfect meal every day, or never eat the same meal twice?",
    "Give up music forever, or give up movies forever?",
    "Give up salty snacks forever, or give up sweet snacks forever?",
    "Have a rewind button for conversations, or a pause button for awkward moments?",
    "Have a personal chef, or have a personal driver?",
    "Have a photographic memory for faces, or for places?",
    "Have free flights anywhere forever, or free meals anywhere forever?",
    "Have more free time, or have more spending money?",
    "Have one extra hour every morning, or one extra hour every night?",
    "Have super hearing, or super smell?",
    "Have the ability to find anything you lose, or never lose anything again?",
    "Have unlimited books, or unlimited board games?",
    "Have wifi everywhere you go, or never need wifi again?",
    "Know every language but only read them, or speak one language perfectly but write poorly?",
    "Know the ending of every book before you start, or never know how a story ends?",
    "Live in a house with a huge yard and a small home, or a huge home and no yard?",
    "Live in a treehouse, or live on a houseboat?",
    "Live next door to your best friend, or live next door to your favorite restaurant?",
    "Live without air conditioning, or live without heating?",
    "Lose your phone for a day, or lose your keys for a day?",
    "Never do laundry again, or never wash dishes again?",
    "Never get a mosquito bite again, or never get sunburned again?",
    "Never have to wait in line, or never hit traffic?",
    "Never need an alarm clock, or never feel tired during the day?",
    "Never use a microwave again, or never use an oven again?",
    "Only eat food you cook, or only eat food someone else cooks?",
    "Only listen to one song on repeat for a month, or only listen to new songs for a month?",
    "Only travel by train, or only travel by plane?",
    "Only watch cartoons, or only watch documentaries?",
    "Read minds but only happy thoughts, or read minds but only worried thoughts?",
    "Read one book a week forever, or watch one movie a week forever?",
    "Ride a bike everywhere, or walk everywhere?",
    "Share one bathroom with five tidy people, or have five messy bathrooms to yourself?",
    "Shower in the morning only, or shower at night only?",
    "Sing every time you speak, or dance every time you walk?",
    "Skip every Monday, or skip every Friday?",
    "Sleep in a hammock, or sleep on a giant beanbag?",
    "Talk to your past self for ten minutes, or your future self for ten minutes?",
    "Trade places with your pet for a day, or trade places with your favorite teacher for a day?",
    "Travel to the past for a week, or travel to the future for a week?",
    "Use only pencils, or use only pens?",
    "Wake up early on weekends, or sleep in on weekdays too?",
    "Watch only live sports, or play only sports and never watch them?",
    "Wear formal clothes every day, or wear pajamas every day?",
    "Win a small prize every day, or win one huge prize once?",
    "Always have cold drinks, or always have hot drinks?",
    "Always have snacks in your pocket, or always have tissues in your pocket?",
    "Always hear background music, or always hear gentle ocean sounds?",
    "Always know when someone is lying, or always know when someone needs help?",
    "Always take the scenic route, or always take the fastest route?",
    "Be able to breathe underwater, or be able to survive in extreme cold?",
    "Be able to draw perfectly, or be able to sing perfectly?",
    "Be able to run as fast as a bike, or bike as comfortably as walking?",
    "Be allergic to chocolate, or be allergic to cheese?",
    "Be great at telling stories, or be great at remembering facts?",
    "Be stuck with dial-up internet for a day, or no phone for a day?",
    "Be the captain of every team, or the cheerleader for every team?",
    "Be the best gift-giver, or be the best thank-you-note writer?",
    "Be the person who picks the restaurant, or the person who always enjoys whatever is picked?",
    "Be too hot all the time, or too cold all the time?",
    "Eat dessert before dinner every night, or never eat dessert again?",
    "Eat pizza every Friday, or eat tacos every Tuesday?",
    "Get a surprise party every year, or plan the perfect party for someone else every year?",
    "Get free tickets to every concert, or free passes to every museum?",
    "Give up all social media, or give up all streaming services?",
    "Give up coffee, or give up tea?",
    "Go camping every month, or go to the beach every month?",
    "Go to space for an hour, or explore the deepest ocean trench for an hour?",
    "Have a clone to do chores, or have a robot to do homework?",
    "Have a home library that restocks itself, or a kitchen that cooks one perfect meal daily?",
    "Have a magic backpack that fits anything, or shoes that never wear out?",
    "Have a pet dragon the size of a cat, or a pet elephant the size of a dog?",
    "Have a phone battery that lasts a week, or a car that never needs gas?",
    "Have a room that cleans itself, or laundry that folds itself?",
    "Have a week with no homework, or a week with no chores?",
    "Have an endless supply of your favorite candy, or your favorite fruit?",
    "Have every Friday off school or work, or have every Wednesday off?",
    "Have perfect handwriting, or type twice as fast?",
    "Have snow on your birthday every year, or sunshine on your birthday every year?",
    "Have the world's best memory for birthdays, or for favorite foods?",
    "Have to whisper for a day, or have to speak in rhyme for a day?",
    "Have your favorite meal once a week, or a pretty good meal every day?",
    "Keep one childhood toy forever, or keep one childhood photo album forever?",
    "Know how to fix any bike, or know how to cook any meal?",
    "Know the history of every place you visit, or know the best food in every place you visit?",
    "Live above a bakery, or live above a bookstore?",
    "Live in a city with great public transit, or live in a town where you can bike everywhere?",
    "Live where it rains every afternoon, or where it is sunny every afternoon?",
    "Lose the ability to taste sweet, or lose the ability to taste salty?",
    "Never eat ice cream again, or never eat french fries again?",
    "Never get hiccups again, or never get the hiccups from laughing too hard?",
    "Never have to set an alarm, or never have to charge your devices?",
    "Never step on a LEGO brick again, or never stub your toe again?",
    "Only eat with chopsticks, or only eat with a spoon?",
    "Only play outside games, or only play inside games?",
    "Only use paper maps, or only use voice directions?",
    "Ride a roller coaster every week, or watch fireworks every week?",
    "See every sunrise for a year, or see every sunset for a year?",
    "Share your room with a sibling who is tidy, or have your own room that is always messy?",
    "Shop only at small local stores, or shop only at huge supermarkets?",
    "Speak every language for one day, or play every instrument for one day?",
    "Spend a day as a zookeeper, or spend a day as a park ranger?",
    "Spend a day in the 1800s, or spend a day in the 2200s?",
    "Spend a week without TV, or spend a week without music?",
    "Swap lives with a cartoon character for a day, or with a historical figure for a day?",
    "Take a photo that lasts forever, or take a trip that lasts one perfect day?",
    "Take only baths, or take only showers?",
    "Talk to plants and hear them reply, or talk to books and hear their stories?",
    "Travel by hot-air balloon, or travel by speedboat?",
    "Use only stairs for a month, or only elevators for a month?",
    "Visit every continent once, or revisit your favorite place ten times?",
    "Wake up to birdsong, or wake up to your favorite song?",
    "Watch a movie with no sound, or listen to a movie with no picture?",
    "Wear socks with sandals confidently, or never wear sandals again?",
    "Win a year of free ice cream, or win a year of free movie tickets?",
    "Always find a parking spot, or always find a seat on public transit?",
    "Always get the last slice of pizza, or always get the first fresh batch?",
    "Always have clean socks, or always have a charged phone?",
    "Always have good hair days, or always have good outfit days?",
    "Always know the shortest line at the store, or always know the fastest checkout clerk?",
    "Be able to jump as high as a basketball hoop, or run as fast as a scooter?",
    "Be able to talk to babies and understand them, or talk to grandparents and hear their best stories?",
    "Be famous on a talent show, or be famous for helping your community?",
    "Be the best at charades, or be the best at riddles?",
    "Be the designated photographer, or be the person who never appears in photos?",
    "Be the friend who remembers birthdays, or the friend who always brings snacks?",
    "Be the teacher's helper for a day, or the coach's helper for a day?",
    "Be too tall for doorways, or too short to reach top shelves?",
    "Bring lunch from home every day, or eat cafeteria food every day?",
    "Build the world's tallest sandcastle, or find the coolest seashell on the beach?",
    "Camp in the mountains, or camp by the ocean?",
    "Carry a huge umbrella always, or never need an umbrella?",
    "Celebrate every holiday twice, or invent one new holiday each year?",
    "Clean your room in five minutes magically, or keep it tidy without thinking?",
    "Climb a real mountain, or kayak a real river?",
    "Cook one meal perfectly, or bake one dessert perfectly?",
    "Dance in public without embarrassment, or sing karaoke without embarrassment?",
    "Discover a new planet, or discover a new species in your backyard?",
    "Do homework in half the time, or chores in half the time?",
    "Drink only smoothies for a week, or only soup for a week?",
    "Eat breakfast for every meal, or dinner for every meal?",
    "Explore a cave, or explore a coral reef?",
    "Find a hidden door in your house, or find a secret garden behind your school?",
    "Fix any broken toy, or build any toy from scratch?",
    "Fly a kite in a storm safely, or sail a boat on a calm lake?",
    "Get a hundred small compliments, or one huge heartfelt compliment?",
    "Get free popcorn at every movie, or free toppings on every ice cream?",
    "Get stickers on every assignment, or get high-fives from every teacher?",
    "Give up video games for a month, or give up board games for a month?",
    "Go on a road trip with no map, or go on a road trip with a strict schedule?",
    "Go to bed at sunset, or go to bed at midnight every night?",
    "Grow the perfect garden, or grow the perfect treehouse?",
    "Have a birthday party every month, or one epic birthday party every year?",
    "Have a bubble machine follow you, or have confetti fall when you enter a room?",
    "Have a friendly ghost as a roommate, or a friendly robot as a roommate?",
    "Have a magic eraser for mistakes, or a magic pencil that never dulls?",
    "Have a pet that can talk, or a plant that gives advice?",
    "Have a slide instead of stairs at home, or a trampoline in the living room?",
    "Have a snow day every week in winter, or a pool day every week in summer?",
    "Have a tree that grows any fruit you want, or a garden that grows any vegetable?",
    "Have an endless supply of markers, or an endless supply of building blocks?",
    "Have every book read to you by a great narrator, or read every book yourself silently?",
    "Have homework that grades itself, or chores that complete themselves?",
    "Have lunch with your favorite athlete, or lunch with your favorite author?",
    "Have matching outfits with your best friend, or never match accidentally again?",
    "Have more snowball fights, or have more water balloon fights?",
    "Have pancakes every morning, or have waffles every morning?",
    "Have pizza delivered by drone, or by bicycle with a bell choir?",
    "Have super sticky shoes for climbing, or super bouncy shoes for jumping?",
    "Have the best seat at every concert, or meet the band after every show?",
    "Have the loudest laugh in the room, or the most contagious smile?",
    "Have the power to make anyone laugh, or the power to calm anyone down?",
    "Have the world's best tree fort, or the world's best blanket fort?",
    "Have to eat with your non-dominant hand, or write with your non-dominant hand?",
    "Have to wear a cape everywhere, or wear a hat everywhere?",
    "Have unlimited craft supplies, or unlimited sports equipment?",
    "Have your favorite animal as a pet, or your favorite vehicle as a toy?",
    "Hear every song before it is released, or read every book before it is published?",
    "Help build a playground, or help plant a community garden?",
    "Hold a snake calmly, or hold a tarantula calmly?",
    "Host a game show at school, or host a cooking show at home?",
    "Jump into a pile of leaves every day, or jump into a pile of pillows every day?",
    "Keep a diary that writes back, or keep a photo album that plays sounds?",
    "Keep every ticket stub forever, or keep every seashell from every beach?",
    "Learn magic tricks, or learn juggling?",
    "Live in a castle with no heating, or a cabin with perfect heating?",
    "Live in a neighborhood with every friend nearby, or live where the food is amazing?",
    "Live where it snows on holidays, or where it is warm on holidays?",
    "Lose power for a day with candles and board games, or lose internet for a day with books?",
    "Make the world's best paper airplane, or make the world's best origami crane?",
    "Meet a dinosaur safely, or meet an astronaut on the moon safely?",
    "Never brush your teeth again but have perfect teeth, or brush twice daily forever?",
    "Never get lost, or never lose your belongings?",
    "Never run out of hot water, or never run out of battery on game night?",
    "Only drink milkshakes, or only drink lemonade?",
    "Only eat finger foods, or only eat foods you eat with a fork?",
    "Only play team sports, or only play solo sports?",
    "Only read comic books, or only read chapter books?",
    "Only use crayons, or only use colored pencils?",
    "Open a lemonade stand that never runs out, or a bake sale that never runs out?",
    "Paint a mural on your school wall, or paint a mural on your bedroom wall?",
    "Pat a penguin, or feed a giraffe?",
    "Pick teams always, or never have to pick teams?",
    "Play hide-and-seek in a museum after hours, or play tag in a giant mall after hours?",
    "Play in the rain without getting cold, or play in the snow without getting wet?",
    "Play one instrument amazingly, or play every instrument a little?",
    "Play outside until dark every day, or play board games inside until dark every day?",
    "Play the hero in every story, or play the clever sidekick in every story?",
    "Read under the covers with a flashlight, or read in a sunny window seat?",
    "Ride a camel, or ride a horse on the beach?",
    "Ride the tallest slide, or ride the longest zip line?",
    "Run a marathon slowly, or sprint a hundred meters incredibly fast?",
    "See a whale up close, or see the northern lights up close?",
    "See your favorite band live once, or see a great unknown band ten times?",
    "Share one giant pizza, or everyone gets their own personal pizza?",
    "Sing in a choir, or play in a band?",
    "Sit in the front row at a show, or sit in the back with the best view?",
    "Skip rope for an hour, or hula hoop for an hour?",
    "Sleep in a tent every weekend, or sleep in a fancy hotel every weekend?",
    "Slide down a banister safely, or swing on a rope swing over a lake?",
    "Smell every flower in a garden, or taste every fruit in an orchard?",
    "Speak to crowds confidently, or perform on stage confidently?",
    "Spend a day at an amusement park alone, or spend a day at a water park with friends?",
    "Spend a day building with LEGO, or spend a day painting?",
    "Spend a night in a museum, or spend a night on a ship?",
    "Start a club at school, or join every club at school?",
    "Stay up late on New Year's Eve every year, or wake up early for sunrise every New Year?",
    "Swim with dolphins, or snorkel with colorful fish?",
    "Take a horse-drawn carriage ride, or take a gondola ride?",
    "Take the window seat on every flight, or take the aisle seat on every flight?",
    "Talk to your favorite fictional character, or talk to your favorite historical hero?",
    "Throw the best surprise party, or receive the best surprise party?",
    "Trade desserts at lunch every day, or keep your desserts secret?",
    "Travel by camel across a desert, or travel by sled across snow?",
    "Use a time machine once, or use a teleporter once?",
    "Visit a volcano safely, or visit a glacier safely?",
    "Visit every zoo in your country, or visit every national park?",
    "Volunteer at an animal shelter, or volunteer at a food bank?",
    "Wake up to pancakes on your birthday only, or wake up to pancakes every Saturday?",
    "Walk on stilts well, or ride a unicycle well?",
    "Watch a meteor shower every month, or watch a rainbow every week?",
    "Watch cartoons from the 1990s, or watch cartoons made this year?",
    "Watch only funny movies, or watch only adventure movies?",
    "Wear a costume to school every Friday, or wear pajamas to school one day a year?",
    "Wear goggles that see underwater, or boots that walk on water?",
    "Win a spelling bee, or win a science fair?",
    "Win at rock-paper-scissors every time, or win at coin flips every time?",
    "Write a bestselling children's book, or illustrate a bestselling children's book?",
    "Always have perfect picnic weather, or always have perfect stargazing weather?",
    "Always pick the right line at the grocery store, or always pick the ripest fruit?",
    "Be able to smell when cookies are done, or hear when the kettle is ready?",
    "Be friends with someone who tells great jokes, or someone who gives great hugs?",
    "Be the fastest reader in class, or the fastest runner at recess?",
    "Bring your pet to school one day, or bring your favorite toy to show-and-tell every week?",
    "Build a robot that does homework, or build a robot that tells jokes?",
    "Catch every ball in a game, or throw every ball perfectly?",
    "Celebrate your birthday in summer every year, or in winter every year?",
    "Choose the music on every car ride, or choose the snacks on every car ride?",
    "Climb the tallest tree in town, or dive into the deepest pool in town?",
    "Collect stamps, or collect interesting rocks?",
    "Color inside the lines perfectly, or draw freestyle masterpieces?",
    "Compete in a friendly talent show, or host the talent show?",
    "Curl up with a cat, or play fetch with a dog?",
    "Dance in the rain, or build a snowman in fresh snow?",
    "Discover buried treasure in your yard, or discover a time capsule at school?",
    "Drink hot cocoa with marshmallows every day, or iced tea every day?",
    "Eat a giant pretzel at a fair, or eat cotton candy at a fair?",
    "Find a four-leaf clover every week, or find a lucky penny every week?",
    "Get a standing ovation once, or make one person deeply happy every day?",
    "Get free ice cream on hot days, or free hot chocolate on cold days?",
    "Go sledding every winter day, or go swimming every summer day?",
    "Grow flowers that change color, or grow vegetables that taste like dessert?",
    "Have a backpack that organizes itself, or shoes that tie themselves?",
    "Have a birthday cake that never runs out for one party, or candles that never melt?",
    "Have a favorite pen that never runs dry, or a favorite notebook that never fills up?",
    "Have a magic carpet for short trips, or roller skates that work on grass?",
    "Have a phone that translates any language instantly, or a map that shows secret paths?",
    "Have a robot that walks your dog, or a dog that fetches your homework?",
    "Have a secret handshake with your best friend, or a secret code for notes?",
    "Have an extra day off every month, or an extra hour of recess every day?",
    "Have dessert first at every restaurant, or never wait for a table?",
    "Have fireworks on your birthday, or balloons everywhere on your birthday?",
    "Have matching pajamas with your family on holidays, or matching hats?",
    "Have more cousins visit often, or visit more cousins often?",
    "Have perfect eyesight, or perfect hearing?",
    "Have the best Halloween costume every year, or the best Christmas sweater every year?",
    "Have the power to freeze a moment for photos, or rewind one embarrassing moment?",
    "Have unlimited stickers, or unlimited temporary tattoos?",
    "Have your bedroom redecorated magically once a year, or pick one perfect theme forever?",
    "Hear a joke that never gets old, or hear a song that never gets old?",
    "Help animals find homes, or help neighbors with groceries?",
    "Jump on a pogo stick across town, or skateboard across town?",
    "Keep a fish that sings, or a bird that tells jokes?",
    "Learn to surf, or learn to ski?",
    "Live near the ocean, or live near the mountains?",
    "Lose one hour of sleep but gain one hour of play, or keep sleep and lose one hour of play?",
    "Make the world's biggest bubble, or the world's longest domino chain?",
    "Meet every Disney character, or meet every superhero?",
    "Never have a bad hair day at school photos, or never have a stain on your shirt?",
    "Only celebrate birthdays, or only celebrate half-birthdays too?",
    "Only play card games, or only play dice games?",
    "Open presents slowly one by one, or open everything at once?",
    "Paint your room any color weekly, or keep one perfect color forever?",
    "Pat every dog you see, or high-five every kid on your team?",
    "Pick the movie every family night, or pick the snacks every family night?",
    "Play chess with a grandmaster, or play soccer with a pro?",
    "Play in a marching band, or cheer from the best spot in the stadium?",
    "Read five short books, or read one long book?",
    "Ride in a parade float, or ride a fire truck with sirens?",
    "Run a lemonade stand that earns enough for a bike, or a bake sale that earns enough for a trip?",
    "See every animal at the zoo in one day, or spend all day with one favorite animal?",
    "Send a message to the whole world for one minute, or send a private message to anyone in history?",
    "Share your favorite snack with the class, or keep a secret stash forever?",
    "Sing the national anthem at a game, or lead a pep rally?",
    "Sit by the campfire every night, or watch the stars from a rooftop every night?",
    "Sleep in on Sundays only, or sleep in on every school holiday?",
    "Slide into home plate safely every time, or hit a home run once?",
    "Spend a day as principal, or spend a day as lunch chef?",
    "Spend a week on a farm, or spend a week in a big city?",
    "Start every morning with stretches, or start every morning with jokes?",
    "Swim in a lake, or swim in a pool?",
    "Take care of a class pet for a month, or adopt a plant for the classroom?",
    "Take photos that always look professional, or draw pictures that always look professional?",
    "Throw a perfect spiral every time, or catch a perfect spiral every time?",
    "Trade lunches with a friend daily, or always pack the perfect lunch?",
    "Travel by scooter everywhere, or travel by skateboard everywhere?",
    "Visit a lighthouse, or visit a windmill?",
    "Wake up to snow on the ground, or wake up to flowers blooming?",
    "Walk your neighbor's dog, or water your neighbor's plants?",
    "Watch a play on stage, or act in a play on stage?",
    "Watch the sunrise from a hill, or watch the sunset from a pier?",
    "Win a friendly debate, or win a friendly race?",
    "Write with your left hand for a day, or hop on one foot for a day?",
]

TABLE_CATEGORIES: list[dict] = [
    {
        "id": "growing-up",
        "title": "Growing up",
        "items": [
            "A rule from childhood you still follow.",
            "A toy or game you wish you still had.",
            "A smell that instantly takes you back to childhood.",
            "A sound from your neighborhood growing up.",
            "A food you loved as a kid that you still love.",
            "A food you hated as a kid that you like now.",
            "A holiday tradition you looked forward to every year.",
            "A chore you actually did not mind doing.",
            "A chore you tried hard to avoid.",
            "A time you got lost and how it turned out.",
            "A teacher who changed how you see something.",
            "A friend from childhood you still think about.",
            "A playground game you could play for hours.",
            "A birthday party you still remember clearly.",
            "A gift you were thrilled to receive as a kid.",
            "A skill you learned young and still use.",
            "A family road trip story worth retelling.",
            "A time you stood up for someone at school.",
            "A time someone stood up for you.",
            "A book you read over and over as a kid.",
            "A cartoon or show that shaped your sense of humor.",
            "A song your family played on repeat.",
            "A nickname you had and whether you liked it.",
            "A superstition or ritual you had as a kid.",
            "A time you were braver than you expected.",
            "A time you were more scared than you expected.",
            "A pet or animal that was part of your childhood.",
            "A tree, hill, or corner of town that felt like yours.",
            "A time you moved homes or schools and what helped.",
            "A hobby you picked up young and dropped.",
            "A hobby you picked up young and kept.",
            "A time you lied and still feel guilty about.",
            "A time you told the truth when it was hard.",
            "A prize or ribbon you earned and what it meant.",
            "A time you failed at something and tried again.",
            "A time you quit something and were glad you did.",
            "A relative who told the best stories.",
            "A meal that only tasted right at someone's house.",
            "A time you shared a room and what you learned.",
            "A time you had your own space and what you did with it.",
            "A weather day you remember — snow, rain, or heat.",
            "A time you built something with your hands.",
            "A time you broke something and had to fix it.",
            "A time you laughed so hard you could not stop.",
            "A time you cried and who comforted you.",
            "A piece of clothing you wore until it fell apart.",
            "A time you felt proud of a sibling or cousin.",
            "A time you felt jealous of a sibling or cousin.",
            "A school project you still remember.",
            "A time you helped a neighbor without being asked.",
        ],
    },
    {
        "id": "places-travel",
        "title": "Places and travel",
        "items": [
            "A place that surprised you when you finally visited.",
            "A place you would take a visitor on their first day in your town.",
            "A trip that did not go as planned but turned out fine.",
            "A trip that went better than planned.",
            "A city you could wander without a map.",
            "A country you want to visit for the food.",
            "A country you want to visit for nature.",
            "A country you want to visit for history.",
            "A beach memory — good or bad.",
            "A mountain or hill climb worth the effort.",
            "A museum exhibit that stuck with you.",
            "A market or fair you loved browsing.",
            "A long flight story — good seat or bad seat.",
            "A train or bus ride you still remember.",
            "A road trip snack tradition.",
            "A souvenir you actually kept and use.",
            "A souvenir you bought and immediately regretted.",
            "A photo from a trip you still look at.",
            "A place you would return to again and again.",
            "A place you would visit once and never need to return.",
            "A hotel or hostel story.",
            "A camping memory — tent, cabin, or backyard.",
            "A time you got wonderfully lost in a new place.",
            "A local food you tried abroad and loved.",
            "A local food you tried abroad and could not finish.",
            "A language barrier moment that became funny.",
            "A time a stranger was kind while you traveled.",
            "A weather surprise on vacation.",
            "A sunrise or sunset you watched on a trip.",
            "A body of water you swam in and remember.",
            "A hike you would recommend to a friend.",
            "A hike you would not recommend.",
            "A theme park ride you would wait in line for again.",
            "A quiet place you found in a busy city.",
            "A festival or parade you stumbled into.",
            "A border or customs story.",
            "A time you traveled light and were glad.",
            "A time you overpacked and paid for it.",
            "A favorite street to walk with no destination.",
            "A view you would paint if you could.",
            "A place that felt peaceful within an hour.",
            "A place that felt overwhelming at first.",
            "A national park or protected area you loved.",
            "A small town that charmed you.",
            "A big city that energized you.",
            "A travel mistake that taught you something.",
            "A travel tip you give everyone.",
            "A place you visited as a kid you want your kids to see.",
            "A bucket-list trip you have not done yet.",
            "A trip you would repeat exactly as it happened.",
        ],
    },
    {
        "id": "food-kitchen",
        "title": "Food and kitchen",
        "items": [
            "A dish you could eat every week without getting tired of it.",
            "A dish you only want on special occasions.",
            "A recipe someone taught you that you still make.",
            "A recipe you ruined the first time you tried.",
            "A food that smells better than it tastes for you.",
            "A food that tastes better than it smells for you.",
            "A comfort food when you are sick.",
            "A comfort food when you are celebrating.",
            "A snack you hide from other people.",
            "A snack you happily share with everyone.",
            "A restaurant you would recommend to anyone.",
            "A restaurant you would not send your worst enemy to.",
            "A street food you would travel for.",
            "A breakfast you could eat any time of day.",
            "A dinner that always makes you sleepy.",
            "A dessert you cannot resist.",
            "A dessert you do not understand the hype for.",
            "A fruit you wait for in season.",
            "A vegetable you learned to like as an adult.",
            "A spice or sauce that changed your cooking.",
            "A kitchen tool you use more than people expect.",
            "A kitchen tool you bought and never use.",
            "A cooking smell that makes a house feel like home.",
            "A food from another culture you love.",
            "A food combination that sounds weird but works.",
            "A food you eat in a specific way every time.",
            "A drink order that says something about you.",
            "A potluck dish you are known for.",
            "A potluck dish you avoid bringing.",
            "A time you cooked for someone and they loved it.",
            "A time you cooked for someone and it went wrong.",
            "A meal you ate alone and enjoyed.",
            "A meal you shared that felt special.",
            "A picnic that was perfect.",
            "A picnic that was a disaster.",
            "A food you tried once and never again.",
            "A food you refused as a kid and love now.",
            "A lunchbox item you still think about.",
            "A midnight snack you are not proud of.",
            "A holiday dish your family argues about.",
            "A baking success you brag about.",
            "A baking failure you laugh about now.",
            "A food you eat differently at home vs. in public.",
            "A condiment you put on almost everything.",
            "A condiment you think is overrated.",
            "A meal that is worth the long wait.",
            "A fast food order you will defend.",
            "A home-cooked meal that beats any restaurant.",
            "A food memory tied to a specific person.",
            "A food you want to learn to cook well.",
        ],
    },
    {
        "id": "hobbies-fun",
        "title": "Hobbies and fun",
        "items": [
            "A hobby you picked up during a boring season of life.",
            "A hobby you quit and sometimes miss.",
            "A game you could play every game night.",
            "A game you refuse to play again.",
            "A sport or activity you are bad at but enjoy.",
            "A sport or activity you are good at but find stressful.",
            "A song you put on when you need energy.",
            "A song you put on when you need calm.",
            "A movie you have seen more than five times.",
            "A movie you walked out of or almost did.",
            "A TV show you recommend to everyone.",
            "A book you gave as a gift.",
            "A book someone gave you that mattered.",
            "A craft or project sitting half-finished at home.",
            "A craft or project you finished and still display.",
            "A concert or live show you still talk about.",
            "A podcast topic you never get tired of.",
            "A board game role you always end up playing.",
            "A video game world you would live in for a week.",
            "A card game you learned as a kid.",
            "A puzzle type you love — jigsaw, crossword, or other.",
            "A collection you had as a kid — cards, rocks, stickers.",
            "A talent you would perform at a school talent show.",
            "A talent you absolutely would not perform.",
            "A hobby that costs more than people think.",
            "A hobby that costs almost nothing.",
            "A weekend activity that never gets old.",
            "A weekend activity you are tired of.",
            "A rainy-day indoor activity you recommend.",
            "A sunny-day outdoor activity you recommend.",
            "A hobby you do alone to recharge.",
            "A hobby you only enjoy with other people.",
            "A instrument you wish you had learned.",
            "A language you wish you had learned.",
            "A YouTube rabbit hole you fall into.",
            "A meme or joke format you still find funny.",
            "A holiday craft or decoration you enjoy making.",
            "A party game that works with any group.",
            "A party game that needs exactly the right group.",
            "A place you go to think — park, café, library.",
            "A creative block you pushed through.",
            "A time you taught someone a game or skill.",
            "A time someone taught you something that stuck.",
            "A competition you won and still smile about.",
            "A competition you lost and still smile about.",
            "A fandom you were deep into.",
            "A character from fiction you relate to.",
            "A hobby you want to try this year.",
            "A hobby you want your kids or nieces to try.",
            "A simple pleasure you wish you did more often.",
        ],
    },
    {
        "id": "family-friends",
        "title": "Family and friends",
        "items": [
            "A friend who feels like family.",
            "A family member who feels like a friend.",
            "A tradition your friend group invented.",
            "A tradition your family refuses to change.",
            "A time a friend made you laugh when you needed it.",
            "A time you made a friend laugh when they needed it.",
            "A piece of advice a parent or elder gave you that stuck.",
            "A piece of advice you give younger people.",
            "A sibling or cousin story that still comes up at reunions.",
            "A reunion moment you look forward to.",
            "A reunion moment you dread a little.",
            "A gift you gave that someone still uses.",
            "A gift you received that surprised you.",
            "A handwritten note or card you kept.",
            "A text or message you re-read sometimes.",
            "A time you apologized and meant it.",
            "A time someone apologized to you and it mattered.",
            "A friend you lost touch with but think of fondly.",
            "A friend you reconnected with and were glad.",
            "A neighbor who made your block better.",
            "A pet that brought your household together.",
            "A pet story your family tells too often.",
            "A meal where everyone talked at once.",
            "A meal where comfortable silence was enough.",
            "A time you hosted and it went well.",
            "A time you hosted and learned a lesson.",
            "A time you were a guest and felt welcomed.",
            "A inside joke only your family understands.",
            "A inside joke only your friends understand.",
            "A time you helped a friend move or fix something.",
            "A time a friend helped you without being asked.",
            "A wedding or celebration you loved attending.",
            "A milestone you are proud someone close achieved.",
            "A hard conversation you are glad you had.",
            "A hard conversation you are still avoiding.",
            "A compliment you remember years later.",
            "A compliment you give easily.",
            "A time you felt like the responsible one in the group.",
            "A time you felt like the chaotic one in the group.",
            "A friend who challenges you to grow.",
            "A friend who helps you relax.",
            "A family recipe or ritual passed down.",
            "A holiday where your people are all in one place.",
            "A long-distance friendship that still works.",
            "A group chat that is mostly memes.",
            "A group chat that is mostly logistics.",
            "A time you met a friend as an adult unexpectedly.",
            "A mentor outside your family who mattered.",
            "A kid in your life who makes you laugh.",
            "A way you stay in touch that actually works.",
        ],
    },
    {
        "id": "stories-surprises",
        "title": "Stories and surprises",
        "items": [
            "A small kindness from a stranger you still remember.",
            "A time you were in the right place at the right time.",
            "A coincidence that still feels unreal.",
            "A dream you remember vividly.",
            "A nightmare that stuck with you.",
            "A near miss — car, bike, kitchen, sports — that taught you something.",
            "A time you found money or lost money in a memorable way.",
            "A prank you pulled that went perfectly.",
            "A prank that backfired on you.",
            "A surprise that made your week.",
            "A surprise you would not want repeated.",
            "A rumor you believed as a kid.",
            "A fact you learned that changed a conversation.",
            "A question a kid asked you that stopped you cold.",
            "A question you wish more people asked.",
            "A time you said yes without knowing what you agreed to.",
            "A time you said no and were relieved.",
            "A costume or outfit you wore proudly.",
            "A costume or outfit you regret.",
            "A weather event you lived through — storm, flood, heat wave.",
            "A power outage story.",
            "A time the internet went out and you did something better.",
            "A thing you believed until embarrassingly late in life.",
            "A superstition you still half believe.",
            "A lucky charm or ritual before big moments.",
            "A unlucky day that became a funny story.",
            "A time you met someone famous or almost did.",
            "A autograph, ticket stub, or keepsake you saved.",
            "A time you were on the news, radio, or school announcement.",
            "A time you helped in an emergency, big or small.",
            "A fear you overcame.",
            "A fear you still have and manage.",
            "A prediction you made that came true.",
            "A prediction you made that failed spectacularly.",
            "A time you guessed someone's secret correctly.",
            "A time your secret got out.",
            "A object you almost threw away and were glad you kept.",
            "A object you kept too long and finally let go.",
            "A sound in your home that still startles you.",
            "A smell in your home that means comfort.",
            "A time you laughed at the wrong moment.",
            "A time silence was the right response.",
            "A rule you break on purpose every time.",
            "A rule you follow even when nobody is watching.",
            "A headline you still think about.",
            "A local legend or story from your town.",
            "A travel story you tell at every dinner party.",
            "A story you shorten every time you tell it.",
            "A story that gets better with every retelling.",
            "A plot twist in your own life you did not see coming.",
        ],
    },
]


def yaml_quote(s: str) -> str:
    if re.search(r'[:#\[\]{},&*?|>!%@`]', s) or s.strip() != s:
        return '"' + s.replace('"', '\\"') + '"'
    return s


def dump_items(items: list[str]) -> str:
    return "\n".join(f"  - {yaml_quote(i)}" for i in items)


def table_topic_items() -> list[str]:
    items: list[str] = []
    for cat in TABLE_CATEGORIES:
        items.extend(cat["items"])
    return items


def build_table_block() -> str:
    items = table_topic_items()
    if len(items) != TARGET:
        raise SystemExit(f"table-topics: need {TARGET} items, have {len(items)}")
    if len(set(items)) != len(items):
        raise SystemExit("table-topics: duplicate items")
    m = TABLE_META
    return (
        f"- id: {m['id']}\n"
        f"  title: {m['title']}\n"
        f"  mode: {m['mode']}\n"
        f"  tagline: {m['tagline']}\n"
        f"  play_hint: {m['play_hint']}\n"
        f"  items:\n{dump_items(items)}\n"
    )


def build_wyr_block() -> str:
    items = WYR_ITEMS[:TARGET]
    if len(items) < TARGET:
        raise SystemExit(f"would-you-rather: need {TARGET}, have {len(items)}")
    if len(set(items)) != len(items):
        raise SystemExit("would-you-rather: duplicate items")
    m = WYR_META
    return (
        f"- id: {m['id']}\n"
        f"  title: {m['title']}\n"
        f"  mode: {m['mode']}\n"
        f"  tagline: {m['tagline']}\n"
        f"  play_hint: {m['play_hint']}\n"
        f"  items:\n{dump_items(items)}\n"
    )


def replace_or_append(text: str, col_id: str, block: str) -> str:
    pattern = rf"- id: {re.escape(col_id)}\n.*?(?=\n- id: |\Z)"
    if re.search(pattern, text, flags=re.S):
        return re.sub(pattern, block.rstrip() + "\n", text, count=1, flags=re.S)
    return text.rstrip() + "\n\n" + block


def main() -> None:
    text = YAML.read_text()
    text = replace_or_append(text, "would-you-rather", build_wyr_block())
    text = replace_or_append(text, "table-topics", build_table_block())
    YAML.write_text(text)
    data = yaml.safe_load(text)
    cols = {c["id"]: c for c in data["collections"]}
    wyr = cols["would-you-rather"]["items"]
    topics = cols["table-topics"]["items"]
    print(f"would-you-rather: {len(wyr)}")
    print(f"table-topics: {len(topics)}")


if __name__ == "__main__":
    main()
