#!/usr/bin/env python3
"""When-clauses for contradicts relationship lines (slug -> qualifier phrase)."""

CONTRADICTS_WHEN: dict[str, str] = {
    # PKM — capture & workflow
    "capture": "I save first and filter later",
    "signal-vs-noise": "I need standing feeds even if most entries are noise this month",
    "pkm": "building the system feels like progress without output",
    "building-a-second-brain": "CODE steps become collection theater with no express",
    "the-collectors-fallacy": "skipping the save kills a spark I'll actually ship from",
    "creative-output": "ship pressure makes me skip capture I'd need for the draft",
    "active-knowledge-curation": "pruning replaces actually shipping",
    "the-trusted-inbox": "one trusted pipe beats frictionless capture everywhere",
    "mobile-capture-workflows": "share sheet beats paper for sparks I might scroll past",
    "analog-capture-tools": "paper wins over fewer digital pipes",
    "context-aware-capture": "inline why beats formal metadata fields",
    "rss-for-research": "appointment reading beats skipping every maybe-save",
    # Linking & structure
    "atomic-notes": "I bury claims inside a hub instead of one file per idea",
    "associative-linking": "links beat sorting by owner and deadline",
    "para-method": "life buckets beat waiting for links to find each other",
    "note-relationships": "typed body links beat sorting by project folder",
    "maps-of-content": "an index gathers claims that should stay atomic",
    "graph-view-analytics": "link counts beat a hand-curated index",
    "mind-mapping": "branches and bubbles beat splitting before I see the shape",
    # Evergreen & lifecycle
    "evergreen-notes": "two-year phrasing beats today's scratch pad",
    "daily-notes": "fleeting capture beats polishing for permanence",
    "evergreen-vs-fleeting-notes": "both lanes beat forcing everything evergreen",
    "the-knowledge-lifecycle": "stage-matched effort beats evergreen polish on every note",
    # Distill & express
    "progressive-summarization": "bold layers beat rewriting into what I believe",
    "synthesis-as-a-goal": "merged belief beats layered highlights on borrowed words",
    "intellectual-sourcing": "citations beat distill-on-demand layers",
    "spaced-repetition": "drill schedules beat bold layers for recall",
    "the-feynman-technique": "explaining gaps beats flashcard drill",
    "creative-blocks": "one ship action beats capturing my way out of stuck",
    "minimum-viable-product": "rough ship beats two-year polish",
    # Mental models & focus
    "pareto-principle": "cutting the long tail kills compounding habits",
    "compounding": "boring repetition beats protecting only the vital few",
    "minimum-effective-dose": "enough-to-work beats stacking past the dose",
    "low-hanging-fruit": "the easy win today beats waiting for the curve to bend",
    "process-over-outcomes": "the daily process beats quarterly scoreboard pressure",
    "there-is-no-perfect-solution": "good-enough tired beats hunting the perfect 20%",
    "mental-models-list": "a model lens beats treating every tradeoff as equal",
    "slow-productivity": "fewer deep projects beat quarterly sprints",
    "the-12-week-year": "quarterly intensity beats fewer deeper projects",
    "periodic-knowledge-review": "calendar review beats the smallest sufficient habit",
    "weekly-review-checklists": "the full checklist beats the smallest review that works",
    "the-second-brain-workflow": "the full loop beats the smallest habit that works",
    # Garden & publishing
    "digital-garden": "public growth beats keeping scraps in the garage",
    "the-garage-concept": "private workshop beats publishing half-baked notes",
    "drafting-in-public": "rough publish beats waiting for evergreen polish",
    "local-first-software": "private-first truth beats publishing before I'm ready",
    "future-proofing-knowledge": "plain exports beat automation-ready structure",
    "building-a-personal-api": "structured context beats fewer moving parts",
    "anti-fragile-systems": "boring files beat tool-coupled structure",
    "metadata-strategy": "light tags beat automation-ready frontmatter",
    "digital-minimalism": "fewer pipes beat building for accidental rediscovery",
    "digital-serendipity": "surprise links beat cutting tools and sync layers",
    "gtd-vs-para": "task inbox truth beats note-garden architecture",
    # Gospel cluster
    "abide-in-me": "I treat spiritual growth as pure self-stacked effort",
    "ask-seek-knock": "anxiety replaces asking",
    "by-their-fruits": "I can't tell fruit from hype",
    "childlike-faith": "I treat faith as a merit account I'm building",
    "dont-worry": "sprint urgency replaces trust",
    "eternal-principles": "I treat gospel ethics as ideas I invented",
    "eternal-rewards": "I treat stacked good works as currency that bought eternal life",
    "first-principles-thinking": "I treat gospel ethics as ideas I invented",
    "forgiveness": "I treat old hurt as debt I'm owed forever",
    "free-grace": "good works compound into a merit ladder I think buys heaven",
    "great-commission": "I hoard truth without sharing it",
    "heart-righteousness": "I polish the outside while nursing anger inside",
    "humility-and-service": "visibility becomes the goal instead of the byproduct",
    "judge-not": "I critique others to elevate myself",
    "let-your-light-shine": "I hide good works out of false modesty",
    "let-your-yes-be-yes": "public words outrun private honesty",
    "love-god": "worry replaces trust",
    "love-your-enemies": "I wait for fair treatment before I act",
    "love-your-neighbor": 'I limit "neighbor" to people I already like',
    "peacemakers": "I confuse peace with never confronting wrong",
    "reconciliation-before-worship": "I prioritize ceremony over the neighbor I've wronged",
    "render-unto-caesar": "I treat the state as ultimate lord",
    "repent-and-believe": "I delay entry until I've fixed myself",
    "secret-devotion": "every act of piety becomes content for applause",
    "seek-the-kingdom-first": "I treat every demand as kingdom-level priority",
    "sunk-cost-fallacy": "I keep collecting on a grudge I should release",
    "take-up-your-cross": "I expect discipleship without cost",
    "the-beatitudes": "pride masquerades as strength",
    "the-golden-rule": "I only apply it to people who already treat me well",
    "the-narrow-way": "I take the comfortable path because everyone else does",
    "the-wise-builder": "I claim Jesus without living his words",
    "treasure-in-heaven": "I hoard earth and call it wisdom",
    "turn-the-other-cheek": "I wait to hit back before acting well",
}

# love-your-neighbor uses "only when" not "when"
ONLY_WHEN_SLUGS = frozenset({"love-your-neighbor"})
